module.exports = {
  apps: [
    {
      name: 'transport-system-backend',
      cwd: '/var/www/transport-system/backend',
      script: '/var/www/transport-system/.venv/bin/gunicorn',
      args: '-c gunicorn.conf.py app:app',
      interpreter: 'none',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      restart_delay: 5000,
      kill_timeout: 10000,
      exp_backoff_restart_delay: 200,
      max_memory_restart: '500M',
      merge_logs: true,
      time: true,
      env: {
        FLASK_ENV: 'production',
        PYTHONUNBUFFERED: '1',
        SOCKETIO_ASYNC_MODE: 'threading',
        GUNICORN_BIND: '127.0.0.1:8000',
        GUNICORN_WORKERS: '3',
        GUNICORN_THREADS: '4',
        GUNICORN_TIMEOUT: '120',
        GUNICORN_KEEPALIVE: '5',
        GUNICORN_MAX_REQUESTS: '1000',
        GUNICORN_MAX_REQUESTS_JITTER: '100',
        API_RATE_LIMIT: '120 per minute',
        RATELIMIT_STORAGE_URI: 'memory://',
        SESSION_COOKIE_SECURE: 'true',
        SESSION_COOKIE_SAMESITE: 'Lax',
      },
    },
    {
      name: 'transport-system-frontend',
      cwd: '/var/www/transport-system/frontend',
      script: 'npx',
      args: 'serve -s dist -l 3000',
      interpreter: 'bash',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      restart_delay: 5000,
      env: {
        NODE_ENV: 'production',
      },
    },
    {
      name: 'transport-system-worker',
      cwd: '/var/www/transport-system/backend',
      script: '/var/www/transport-system/.venv/bin/celery',
      args: '-A tasks.celery_app worker --loglevel=info --concurrency=2',
      interpreter: 'none',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      restart_delay: 5000,
      max_memory_restart: '450M',
      merge_logs: true,
      time: true,
      env: {
        FLASK_ENV: 'production',
        PYTHONUNBUFFERED: '1',
        CELERY_BROKER_URL: 'redis://127.0.0.1:6379/0',
        CELERY_RESULT_BACKEND: 'redis://127.0.0.1:6379/1',
      },
    },
    {
      name: 'transport-system-beat',
      cwd: '/var/www/transport-system/backend',
      script: '/var/www/transport-system/.venv/bin/celery',
      args: '-A tasks.celery_app beat --loglevel=info',
      interpreter: 'none',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      restart_delay: 5000,
      max_memory_restart: '250M',
      merge_logs: true,
      time: true,
      env: {
        FLASK_ENV: 'production',
        PYTHONUNBUFFERED: '1',
        CELERY_BROKER_URL: 'redis://127.0.0.1:6379/0',
        CELERY_RESULT_BACKEND: 'redis://127.0.0.1:6379/1',
      },
    },
  ],
}
